@startuml "Disk"

[*] -down-> 空闲
[*] -down-> 可存
[*] -down-> 已满

空闲 -down-> 待确认
空闲 -> 宕机
空闲 -> 可存

待确认 -up-> 可存


可存 -> 已满
可存 -> 宕机


已满 -> 宕机

已满 -down-> 负载均衡

state c <<choice>>

宕机 -down-> c

c -down-> 硬件损坏 : [硬件级检测]
硬件损坏 -down-> [*]


c -down-> 高负载 : [软件级检测]
高负载 -left-> 负载均衡


负载均衡 -down-> [*]

@enduml