@startuml "组件图"

component [Master Backup] as master_backup

component [Master] as master

component [Authentication] as authentication

component [Client] as client

component [Chunkserver] as chunkserver

component [Database] as db

interface "RPC" as rpc_m
interface "RPC" as rpc_cs
interface "API" as api
interface "Authentication" as auth
interface "Controller" as controller
interface "Feedback" as feedback

master .up.> master_backup : 传输备份
master -down- feedback
master -- rpc_m : 进行通信
master .-> rpc_cs

chunkserver -- rpc_cs : 进行通信
chunkserver -- controller

client ..> controller
client ..> auth
client ..> rpc_m
client -right- api

authentication .up.> feedback
authentication -right- auth
authentication .down.> db




@enduml