@startuml "组件图"

component [Master Backup] as master_backup

component [Master] as master

component [Authentication] as authentication

component [Client] as client

component [Chunkserver] as chunkserver

component [Database] as db

interface "RPC" as rpc_m
interface "RPC" as rpc_cs
interface "API" as api

master .up.> master_backup : 传输备份
master .right.> chunkserver
master -up- rpc_m : 进行通信

chunkserver -up- rpc_cs : 进行通信
chunkserver .down.> client

client .up.> chunkserver
client .left.> authentication

authentication .up.> master
authentication .down.> db

client -down- api

@enduml