@startuml "Usecase"
left to right direction
actor "游客" as USER
actor "MasterServer" as master_server
actor "Chunkserver" as chunkserver

usecase "注册" as Register
usecase "登录" as Login
usecase "安全验证" as Verification
usecase "找回密码" as Recover
usecase "自动登录" as Automatic_login
usecase "邮箱验证" as Email

USER -down-> Register

Email .up.> Register : <<include>>
Verification .up.> Login : <<include>>
Recover .up.> Login : <<extends>>
Automatic_login .up.> Login : <<extends>>

actor "管理员" as ADMIN
actor "用户" as R_USER

R_USER <|-- ADMIN
R_USER <|-- USER
R_USER ->Login 
ADMIN -> Login

package 管理功能 {
  usecase "审查举报信息" as check_File
  usecase "添加用户" as ADD_USER
  usecase "删除用户" as DELETE_USER
  usecase "用户列表" as LIST_USER
  usecase "查询用户信息" as Search_UserInfo
  usecase "查看用户文件" as Search_File
  usecase "删除文件" as Delete_file

  Search_File .up.> Search_UserInfo : <<extends>>
  Delete_file .> Search_File : <<extends>>
  Delete_file .up.> check_File : <<extends>>
  Delete_file .up.> DELETE_USER : <<include>>
}

ADMIN -down-> ADD_USER
ADMIN -down-> DELETE_USER
ADMIN -down-> LIST_USER
ADMIN -down-> Search_UserInfo
ADMIN -down-> check_File

usecase "文件上传" as UPLOAD
usecase "文件下载" as DOWNLOAD
usecase "完整性校验" as data_checksum
usecase "Namespace 管理" as namespace_management
usecase "文件快照" as snapshot
DOWNLOAD .left.> data_checksum : <<include>>

master_server -left-> namespace_management
master_server -left-> data_checksum
master_server -left-> snapshot

usecase "文件修改" as UPDATE
usecase "文件删除" as DELETE
usecase "文件分享" as SHARE
usecase "文件列表" as FILE_LIST
usecase "按时间排序" as sort_by_time
usecase "按大小排序" as sort_by_size

sort_by_size -up-> FILE_LIST
sort_by_time -up-> FILE_LIST

usecase "数据备份" as data_backup

chunkserver --> data_backup



usecase "查看分享文件" as Browse_share

R_USER -up-> UPLOAD
R_USER -up-> DOWNLOAD
R_USER -up->UPDATE
R_USER -up->DELETE
R_USER -up->SHARE
R_USER -up->Browse_share
R_USER -up->FILE_LIST

usecase "文件保存" as PRESERVE
usecase "生成链接" as LINK
usecase "时间排序" as TIME_SORT
usecase "大小排序" as SIZE_SORT
usecase "文件克隆" as File_clone
usecase "举报" as report

LINK .down.> SHARE : <<include>>
PRESERVE .down.> UPDATE : <<include>>
PRESERVE .down.> UPLOAD : <<include>>
File_clone .down.> Browse_share : <<extends>>
report .down.> Browse_share : <<extends>>

TIME_SORT -down-|> FILE_LIST
SIZE_SORT -down-|> FILE_LIST

usecase "文件加密" as ENCRYPTION
usecase "设置有效期" as Validity

ENCRYPTION .down.> PRESERVE : <<extends>>
Validity .down.> LINK : <<include>>


PRESERVE ..> data_backup : <<include>>
DELETE ..> data_backup : <<include>>

@enduml