@startuml "用例图"
left to right direction
actor "游客" as USER

usecase "注册" as Register
usecase "登录" as Login
usecase "安全验证" as Verification
usecase "找回密码" as Recover
usecase "自动登录" as Automatic_login
usecase "邮箱验证" as Email

USER -down-> Register

Email .up.> Register : <<include>>
Verification .up.> Login : <<include>>
Recover .up.> Login : <<extends>>
Automatic_login .up.> Login : <<extends>>

actor "管理员" as ADMIN
actor "用户" as R_USER

R_USER <|-- ADMIN
R_USER <|-- USER
R_USER ->Login 
ADMIN -> Login

package 管理功能 {
  usecase "添加用户" as ADD_USER
  usecase "删除用户" as DELETE_USER
  usecase "用户列表" as LIST_USER
  usecase "删除文件" as Delete_file

  Delete_file .up.> DELETE_USER : <<include>>
}

ADMIN -down-> ADD_USER
ADMIN -down-> DELETE_USER
ADMIN -down-> LIST_USER

usecase "文件上传" as UPLOAD
usecase "文件下载" as DOWNLOAD
usecase "文件修改" as UPDATE
usecase "文件删除" as DELETE
usecase "文件分享" as SHARE
usecase "文件列表" as FILE_LIST
usecase "文件克隆" as File_clone

R_USER -up-> UPLOAD
R_USER -up-> DOWNLOAD
R_USER -up->UPDATE
R_USER -up->DELETE
R_USER -up->SHARE
R_USER -up->FILE_LIST
R_USER -up->File_clone

usecase "文件保存" as PRESERVE
usecase "生成链接" as LINK
usecase "时间排序" as TIME_SORT
usecase "大小排序" as SIZE_SORT

LINK .down.> SHARE : <<include>>
PRESERVE .down.> UPDATE : <<include>>
PRESERVE .down.> UPLOAD : <<include>>

TIME_SORT -down-|> FILE_LIST
SIZE_SORT -down-|> FILE_LIST

usecase "文件加密" as ENCRYPTION
usecase "设置有效期" as Validity

ENCRYPTION .down.> PRESERVE : <<extends>>
Validity .down.> LINK : <<include>>

@enduml