@startuml "活动图 - Master Function"
start

    :Namespcae 管理;
    note left
        例子：
        /d1/d2/leaf
                到
        /a1/d2/leaf
    end note
    note right
        允许并发
        R-L 锁提供了 路径重命名 移除 快照的功能
        文件名序列化允许了多重创建 相同名称的文件
        序列化处理防止了死锁
    end note

    :Create file;
    :Read lock 读锁
        /d1
        /a1/d2;
    :Write lock 写锁
       /d1/d2/leaf;

end
@enduml