@startuml "活动图"


if(已注册?) then (Yes)

else(No)
  repeat
    :注册;
    backward: 还未完成;
  repeat while(完成?)
endif

:登录;


  :权限校验;


  fork
    :下载;
  fork again
    :上传;
  fork again
    :罗列;
  fork again
    :删除;
  end fork

:End;
@enduml

