@startuml "活动图 - Download"

|Client|
start
:确定文件;

|Master|
:搜索 Namespace;

|ChunkServer|
-> 下发指令;
:文件索引;

|Master|
-> 返回;
:请求下载;

|ChunkServer|
-> 向最新的replica或者最近的replica;
:准备传输文件;

|Client|
-> 数据流;
end
@enduml