@startuml "Delete"

|Client|
start
:删除;
note left
    类似于上传但是将所有的
    块 名称设置为日期标签的格式
    让文件成为隐藏文件并等待删除
end note

|Master|
:remove - 删除所有的块;

|ChunkServer|
-> 对所有的 replicas;
:remove;

|Master|
partition 垃圾回收 {
    fork
        :remove - metadata;
    fork again
        :remove - orphaned chunks 孤立块;

        :remove metadata;

        -> heartbeat 心跳包到所有的 replica;
        :通知可以删除此文件;
    end fork
    

}

|Client|
end

@enduml