@startuml "活动图 - Upload"

|Client|
:请求租约 Lease;

|Master|
:检查是否存在并分配 replica;

|Client|
-> 确认其他的 replica 的位置;
:缓存位置信息;

|Chunkserver|
-> 推送数据流;
:所有的 replica 服务器;

|Client|
-> 确认;
:收到确认信息;

|Chunkserver|
:主 replica;
-> 推送到所有服务器;
:次 replica;
-> 通知;
:按照顺序解决 'mutation';

|Client|
-> Primary 服务器发送完成信息
如果有错误也一并返回;
end

@enduml